### ISSUE TITLE
Install PR-No. only for selected repo

### ISSUE THREAD

**Issue by nfsprodriver** [ubports/ubports-qa-scripts#13]
The current behaviour of the qa-scripts I experienced is, that PR installations work now, but the PRs of the selected number is installed from all repos with an existing PR of that number. Maybe there's a way to not just create a PR-No. branch for pull requests but a repo-PR-No. branch so the packages get separated.

**Comment by UniversalSuperBox** [comment]
@mariogrip, this is probably a bug in the build scripts. Should we fix this and continue to deploy to repo or explore other options (like getting the artifacts from Jenkins)?

**Comment by UniversalSuperBox** [comment]
This was fixed by https://github.com/ubports/build-tools/pull/29, which changed PR builds to a new `PR_[repository]_[build number]` syntax. We still do a `dist-upgrade` for all packages, but only the packages built by the single PR are included any more.
