### ISSUE TITLE
ubportrs-qa list shows no entries

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-qa-scripts#5]
After installing a branch ppa with `ubports-qa install` the command `list `would not show anything.

But `update `works...

**Comment by doniks** [comment]
I can confirm that `install` works, but `list` doesn't 

```
sudo ubports-qa install xenial_-_qa-scripts_autocompletion
cat /etc/apt/sources.list.d/ubports-xenial_-_qa-scripts_autocompletion.list
deb http://repo.ubports.com/ xenial_-_qa-scripts_autocompletion main
```

and I actually get the right package installed, but `ubports-qa list` remains empty.

**Comment by Fuseteam** [comment]
Is still still an issue, i can reproduce this on the nexus 5 and the bq e5 afaict

**Comment by Fuseteam** [comment]
darn typo, i meant to say i **can't** reproduce this on the nexus 5 and the bq e5

**Comment by Flohack74** [comment]
No :)
